navbar con login y creacion de cuenta
BealeStBluesBoy/balneario pull request #2
Opened 2020-09-20 02:26 UTC by SoraireEmmanuel

Aqui va el login en el navbar, tambien agregue el registrar. Una sola cosa para verlo ejecuten ng serve en la carpeta angularapp enn el puerto 4200 o sino  lo van a tener que compilar para verlo en django

2020-09-20 03:41 UTC, maxiKapko approved these changes

2020-09-20 16:23 UTC, BealeStBluesBoy requested changes

2020-09-20 16:23 UTC, BealeStBluesBoy commented on frontend/angularapp/src/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Varela+Round">
No va a funcionar en Django porque no carga el index.html, carga el base.html de templates, tenes dos opciones:

- Usar paquetes para angular como [angular-fontawesome](https://github.com/FortAwesome/angular-fontawesome), [ng-bootstrap](https://ng-bootstrap.github.io/#/home), de los iconos y las fuentes no pude encontrar paquete.
- O podes modificar el base.html que esta en templates.

2020-09-20 20:36 UTC, SoraireEmmanuel commented on frontend/angularapp/src/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Varela+Round">
Listo, para solucionar el problema ya que no todas las librerías tienen un instalador en Angular y no quería modificar el bas.html copie físicamente las mismas en la carpeta assets y luego las agregue manualmente en Angular.json. Aparecen tantas correcciones porque mis plugin de visual studio code me ordena el codigo jaja!! sorry!

2020-09-20 20:48 UTC, SoraireEmmanuel commented on frontend/angularapp/src/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Varela+Round">
Arregle el problema de que no se desplegaba el cuadro para logear y registrarse

2020-09-21 01:43 UTC, BealeStBluesBoy approved these changes

2020-09-21 01:44 UTC, merged